#include "tinygpu/compiler/codegen.h"

#include <array>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>

namespace tinygpu::compiler {
namespace {

struct FieldLayout {
    const Type *type = nullptr;
    std::uint8_t offset = 0;
};

struct Value {
    std::uint8_t reg = 0;
    bool temporary = false;
};

struct TypeLayout {
    std::uint32_t size = 0;
    std::uint32_t alignment = 1;
};

class Generator {
public:
    explicit Generator(std::vector<std::string> *diagnostics)
        : diagnostics_(diagnostics)
    {
    }

    std::string run(const TranslationUnit &unit)
    {
        if (diagnostics_) {
            diagnostics_->clear();
        }
        if (!unit.main_function) {
            fail("missing main function");
        }
        build_global_layout(unit);
        emit("; generated by tinygpu-cc");
        emit("; global parameter block begins at data-memory address 0");
        for (const auto &stmt : unit.main_function->body) {
            generate_stmt(*stmt);
        }
        if (!ends_with_ret_) {
            emit("RET");
        }
        return output_.str();
    }

private:
    [[noreturn]] void fail(const std::string &message)
    {
        if (diagnostics_) {
            diagnostics_->push_back(message);
        }
        throw std::runtime_error(message);
    }

    void emit(const std::string &line)
    {
        output_ << line << '\n';
    }

    std::string reg(std::uint8_t value) const
    {
        return "R" + std::to_string(value);
    }

    std::string label(const std::string &prefix)
    {
        return ".L" + prefix + std::to_string(next_label_++);
    }

    static std::uint32_t align_up(std::uint32_t offset, std::uint32_t alignment)
    {
        return (offset + alignment - 1) / alignment * alignment;
    }

    static TypeLayout type_layout(const Type &type)
    {
        switch (type.kind) {
        case TypeKind::U8:
            return {1, 1};
        case TypeKind::Pointer:
            // TinyGPU has an 8-bit data-memory address. Its target pointer ABI
            // therefore uses one-byte pointers with one-byte alignment.
            return {1, 1};
        case TypeKind::Array: {
            const TypeLayout element = type_layout(*type.element);
            return {type.array_size * element.size, element.alignment};
        }
        }
        return {};
    }

    void build_global_layout(const TranslationUnit &unit)
    {
        if (unit.globals.size() > 1) {
            fail("only one global parameter structure is supported");
        }
        if (unit.globals.empty()) {
            return;
        }
        global_name_ = unit.globals.front().name;
        std::uint32_t offset = 0;
        for (const auto &field : unit.globals.front().fields) {
            const TypeLayout layout = type_layout(field.type);
            offset = align_up(offset, layout.alignment);
            if (offset + layout.size > 256) {
                fail("global parameter structure exceeds 256-byte data memory");
            }
            if (!fields_.emplace(
                    field.name,
                    FieldLayout{&field.type, static_cast<std::uint8_t>(offset)}).second) {
                fail("duplicate global field '" + field.name + "'");
            }
            offset += layout.size;
        }
    }

    Value allocate_temp()
    {
        for (std::uint8_t candidate = 0; candidate < used_.size(); ++candidate) {
            if (!used_[candidate]) {
                used_[candidate] = true;
                return {candidate, true};
            }
        }
        fail("expression needs more than 13 writable registers");
    }

    std::uint8_t allocate_local(const std::string &name)
    {
        if (locals_.count(name)) {
            fail("duplicate local variable '" + name + "'");
        }
        Value value = allocate_temp();
        locals_.emplace(name, value.reg);
        return value.reg;
    }

    void release(Value value)
    {
        if (value.temporary) {
            used_[value.reg] = false;
        }
    }

    void copy_to(std::uint8_t destination, Value source)
    {
        if (destination != source.reg) {
            Value zero = allocate_temp();
            emit("CONST " + reg(zero.reg) + ", #0");
            emit("ADD " + reg(destination) + ", " + reg(source.reg) + ", " +
                 reg(zero.reg));
            release(zero);
        }
        release(source);
    }

    const FieldLayout &field(const MemberExpr &member)
    {
        const auto *base = dynamic_cast<const IdentifierExpr *>(member.base.get());
        if (!base || base->name != global_name_) {
            fail("member access must use the global parameter name '" + global_name_ + "'");
        }
        const auto found = fields_.find(member.member);
        if (found == fields_.end()) {
            fail("unknown global field '" + member.member + "'");
        }
        return found->second;
    }

    Value generate_address(const Expr &expr)
    {
        if (const auto *member = dynamic_cast<const MemberExpr *>(&expr)) {
            const auto &layout = field(*member);
            Value address = allocate_temp();
            emit("CONST " + reg(address.reg) + ", #" + std::to_string(layout.offset));
            return address;
        }
        if (const auto *index = dynamic_cast<const IndexExpr *>(&expr)) {
            Value base;
            if (const auto *member = dynamic_cast<const MemberExpr *>(index->base.get());
                member && field(*member).type->kind == TypeKind::Array) {
                base = generate_address(*member);
            } else {
                base = generate_expr(*index->base);
            }
            Value subscript = generate_expr(*index->index);
            Value address = base.temporary ? base : allocate_temp();
            emit("ADD " + reg(address.reg) + ", " + reg(base.reg) + ", " +
                 reg(subscript.reg));
            if (address.reg != base.reg) {
                release(base);
            }
            release(subscript);
            return address;
        }
        if (const auto *unary = dynamic_cast<const UnaryExpr *>(&expr);
            unary && unary->op == UnaryOp::Dereference) {
            return generate_expr(*unary->operand);
        }
        fail("expression is not an addressable global-memory object");
    }

    Value generate_expr(const Expr &expr)
    {
        if (const auto *number = dynamic_cast<const NumberExpr *>(&expr)) {
            if (number->value > 255) {
                fail("u8 constant exceeds 255");
            }
            Value result = allocate_temp();
            emit("CONST " + reg(result.reg) + ", #" + std::to_string(number->value));
            return result;
        }
        if (const auto *identifier = dynamic_cast<const IdentifierExpr *>(&expr)) {
            const auto found = locals_.find(identifier->name);
            if (found != locals_.end()) {
                return {found->second, false};
            }
            if (identifier->name == "blockIdx") {
                return {13, false};
            }
            if (identifier->name == "blockDim") {
                return {14, false};
            }
            if (identifier->name == "threadIdx") {
                return {15, false};
            }
            fail("unknown local variable or builtin '" + identifier->name + "'");
        }
        if (const auto *member = dynamic_cast<const MemberExpr *>(&expr)) {
            Value result = generate_address(*member);
            if (field(*member).type->kind == TypeKind::Array) {
                return result;
            }
            emit("LDR " + reg(result.reg) + ", " + reg(result.reg));
            return result;
        }
        if (const auto *index = dynamic_cast<const IndexExpr *>(&expr)) {
            Value result = generate_address(*index);
            emit("LDR " + reg(result.reg) + ", " + reg(result.reg));
            return result;
        }
        if (const auto *unary = dynamic_cast<const UnaryExpr *>(&expr)) {
            if (unary->op == UnaryOp::AddressOf) {
                return generate_address(*unary->operand);
            }
            Value operand = generate_expr(*unary->operand);
            if (unary->op == UnaryOp::Dereference) {
                Value result = operand.temporary ? operand : allocate_temp();
                if (result.reg != operand.reg) {
                    copy_to(result.reg, operand);
                }
                emit("LDR " + reg(result.reg) + ", " + reg(result.reg));
                return result;
            }
            if (unary->op == UnaryOp::Minus) {
                Value result = allocate_temp();
                emit("CONST " + reg(result.reg) + ", #0");
                emit("SUB " + reg(result.reg) + ", " + reg(result.reg) + ", " +
                     reg(operand.reg));
                release(operand);
                return result;
            }
            return operand;
        }
        if (const auto *binary = dynamic_cast<const BinaryExpr *>(&expr)) {
            Value lhs = generate_expr(*binary->lhs);
            Value rhs = generate_expr(*binary->rhs);
            Value result = lhs.temporary ? lhs : allocate_temp();
            const char *mnemonic = nullptr;
            switch (binary->op) {
            case BinaryOp::Add: mnemonic = "ADD"; break;
            case BinaryOp::Subtract: mnemonic = "SUB"; break;
            case BinaryOp::Multiply: mnemonic = "MUL"; break;
            case BinaryOp::Divide: mnemonic = "DIV"; break;
            }
            emit(std::string(mnemonic) + " " + reg(result.reg) + ", " + reg(lhs.reg) +
                 ", " + reg(rhs.reg));
            if (result.reg != lhs.reg) {
                release(lhs);
            }
            release(rhs);
            return result;
        }
        fail("unsupported expression in TinyGPU backend");
    }

    void generate_condition_branch(const Expr &condition, const std::string &false_label)
    {
        Value value = generate_expr(condition);
        Value zero = allocate_temp();
        emit("CONST " + reg(zero.reg) + ", #0");
        emit("CMP " + reg(value.reg) + ", " + reg(zero.reg));
        emit("BRz " + false_label);
        release(value);
        release(zero);
    }

    void generate_block(const BlockStmt &block)
    {
        for (const auto &stmt : block.body) {
            generate_stmt(*stmt);
        }
    }

    void generate_stmt(const Stmt &stmt)
    {
        ends_with_ret_ = false;
        if (const auto *declaration = dynamic_cast<const VarDecl *>(&stmt)) {
            if (declaration->type.kind == TypeKind::Array) {
                fail("local arrays are not supported by the first backend; place the array in global parameters");
            }
            const std::uint8_t destination = allocate_local(declaration->name);
            if (declaration->init) {
                copy_to(destination, generate_expr(*declaration->init));
            } else {
                emit("CONST " + reg(destination) + ", #0");
            }
            return;
        }
        if (const auto *assignment = dynamic_cast<const AssignStmt *>(&stmt)) {
            Value value = generate_expr(*assignment->value);
            if (const auto *identifier =
                    dynamic_cast<const IdentifierExpr *>(assignment->target.get())) {
                const auto found = locals_.find(identifier->name);
                if (found == locals_.end()) {
                    fail("assignment target is not a writable local variable '" +
                         identifier->name + "'");
                }
                copy_to(found->second, value);
            } else {
                Value address = generate_address(*assignment->target);
                emit("STR " + reg(address.reg) + ", " + reg(value.reg));
                release(address);
                release(value);
            }
            return;
        }
        if (const auto *expression = dynamic_cast<const ExprStmt *>(&stmt)) {
            release(generate_expr(*expression->expr));
            return;
        }
        if (dynamic_cast<const ReturnStmt *>(&stmt)) {
            emit("RET");
            ends_with_ret_ = true;
            return;
        }
        if (const auto *block = dynamic_cast<const BlockStmt *>(&stmt)) {
            generate_block(*block);
            return;
        }
        if (const auto *conditional = dynamic_cast<const IfStmt *>(&stmt)) {
            const std::string else_label = label("else");
            const std::string join_label = label("join");
            generate_condition_branch(*conditional->condition,
                                      conditional->else_block ? else_label : join_label);
            generate_block(*conditional->then_block);
            if (conditional->else_block) {
                emit("BR " + join_label);
                emit(else_label + ":");
                generate_block(*conditional->else_block);
            }
            emit(join_label + ":");
            emit("JOIN");
            return;
        }
        if (const auto *loop = dynamic_cast<const WhileStmt *>(&stmt)) {
            const std::string head = label("while");
            const std::string done = label("wend");
            emit(head + ":");
            generate_condition_branch(*loop->condition, done);
            generate_block(*loop->body);
            emit("BR " + head);
            emit(done + ":");
            emit("JOIN");
            return;
        }
        if (const auto *loop = dynamic_cast<const ForStmt *>(&stmt)) {
            if (loop->init) {
                generate_stmt(*loop->init);
            }
            const std::string head = label("for");
            const std::string done = label("fend");
            emit(head + ":");
            if (loop->condition) {
                generate_condition_branch(*loop->condition, done);
            }
            generate_block(*loop->body);
            if (loop->step) {
                generate_stmt(*loop->step);
            }
            emit("BR " + head);
            emit(done + ":");
            emit("JOIN");
            return;
        }
        fail("unsupported statement in TinyGPU backend");
    }

    std::vector<std::string> *diagnostics_;
    std::ostringstream output_;
    std::array<bool, 13> used_{};
    std::unordered_map<std::string, std::uint8_t> locals_;
    std::unordered_map<std::string, FieldLayout> fields_;
    std::string global_name_;
    std::size_t next_label_ = 0;
    bool ends_with_ret_ = false;
};

}  // namespace

std::string generate_assembly(const TranslationUnit &unit,
                              std::vector<std::string> *diagnostics)
{
    try {
        return Generator(diagnostics).run(unit);
    } catch (const std::runtime_error &) {
        return {};
    }
}

}  // namespace tinygpu::compiler
