; generated by tinygpu-cc
; global parameter block begins at data-memory address 0
MUL R1, R13, R14
ADD R1, R1, R15
CONST R2, #0
ADD R0, R1, R2
CONST R1, #0
LDR R1, R1
ADD R1, R1, R0
LDR R1, R1
CONST R2, #1
LDR R2, R2
ADD R2, R2, R0
LDR R2, R2
ADD R1, R1, R2
CONST R2, #2
LDR R2, R2
ADD R2, R2, R0
STR R2, R1
RET
